name: test deploy
on:
  push:
    branches:
      - main
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pull and checkout from git repository
        run:  |
          echo "pulling and checkout out from git repository"
          